version: '3.6'

services:
    php:
        build:
            context: docker/php
            args:
                PHP_VERSION: 7.4
                USER_GID: 1000
                USER_UID: 1000
        restart: always
        volumes:
            - .:/srv:rw
